# Generated by Django 5.2.9 on 2025-12-21 00:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("ts", models.DateTimeField(default=django.utils.timezone.now)),
                ("actor", models.CharField(blank=True, max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="TaskDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        max_length=32,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("definition", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="TaskType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "image"), ("video_frame", "video_frame")],
                        default="image",
                        max_length=20,
                    ),
                ),
                (
                    "s3_key",
                    models.CharField(
                        help_text="S3 object key (not a presigned URL).", max_length=512
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True, help_text="Optional content hash.", max_length=64
                    ),
                ),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("in_progress", "in_progress"),
                            ("complete", "complete"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="Per-task extra config."
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.asset",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.project",
                    ),
                ),
                (
                    "task_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="core.taskdefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("backend", models.CharField(default="mturk", max_length=32)),
                ("hit_id", models.CharField(blank=True, max_length=128)),
                ("assignment_id", models.CharField(blank=True, max_length=128)),
                ("worker_id", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("submitted", "submitted"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("expired", "expired"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("sandbox", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw MTurk payload snapshots.",
                    ),
                ),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.JSONField()),
                ("schema_version", models.CharField(max_length=32)),
                ("tool_version", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.CharField(
                        blank=True,
                        help_text="Optional session/worker identifier.",
                        max_length=128,
                    ),
                ),
                (
                    "submission_id",
                    models.CharField(
                        blank=True,
                        help_text="Idempotency key (e.g., MTurk assignment or client-provided UUID).",
                        max_length=128,
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw submission payload for audit.",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source assignment if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annotations",
                        to="core.assignment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="core.task",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="taskdefinition",
            name="task_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="definitions",
                to="core.tasktype",
            ),
        ),
        migrations.CreateModel(
            name="FrontendPlugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("version", models.CharField(max_length=32)),
                ("manifest", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "task_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin",
                        to="core.tasktype",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["project", "media_type"], name="asset_proj_media_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["backend", "hit_id"], name="asgn_backend_hit_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["assignment_id"], name="asgn_assignment_idx"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["task", "status"], name="asgn_task_status_idx"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["status", "updated_at"], name="asgn_status_updated_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("assignment_id", ""), _negated=True),
                fields=("backend", "assignment_id"),
                name="uniq_backend_assignment_id",
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["task", "created_at"], name="anno_task_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(fields=["submission_id"], name="anno_submission_idx"),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("submission_id", ""), _negated=True),
                fields=("task", "submission_id"),
                name="uniq_task_submission_id",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "status"], name="task_proj_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["created_at"], name="task_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="taskdefinition",
            index=models.Index(
                fields=["task_type", "version"], name="taskdef_type_ver_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskdefinition",
            unique_together={("task_type", "version")},
        ),
    ]
